// See https://aka.ms/new-console-template for more information
using Asample.Day1;
using Asample.Day2;
using Asample.Day3;
//using Asample.Day5;
using Asample.Day6;
using Asample.Day7;
using Asample.Day8;
//using Asample.Day4;
//TestEnum.TestMovieRating();
//Calculator.Add();
//Password.DoLogin();
//Password.DoLogin();
//Numdes.pattern();
//TestBox.TestOne();
//BoxTester.TestOne();
//BoxTester.TestTwo();
//BoxTester.TestThree();
//ExceptionDemo.DemoAExceptions();
//VehicleTester.TestOne();
//MediaTester.TestOne();
//ExceptionDemo.TestCatchFinally();
//ExceptionDemo.TestStackTrace();
//ExceptionDemo..NestedTryDemo();


//int v1 = 1000;
//Console.WriteLine($"v1:{v1}");
//DoTask.Dotask(v1);
//Console.WriteLine($"v1:{v1}");
//DoTask.DoTaskA(ref v1);
//Console.WriteLine($"v1:{v1}");

//Anagrams.Anagram();
//SetDemoExp.SetDemoA();
//QueueDemo.TestQueue();
//DictionaryDemo.HashtableDemo();
//DictionaryDemo.EmpHTDemo();
//DictionaryDemo.EmpDictionaryDemo();
//DictionaryDemo.TestSortedListA();
//DictionaryDemo.TestSortedListOfEmp();
//WorkingWithObjects.TestOne();
//WorkingWithObjects.TestTwo();
//BoxGeneric.TestA();
//ParametersDemo.TestByRefMethod();
//ParametersDemo.TestOptionalParameter();
//ParametersDemo.AddIntParameters();
//ParametersDemo.TestAddIntParams();
//TestEmp.TestA();
//DelegateDemo.TestOne();
//LamdaDemo.DemoA();
//LamdaDemo.DemoB();
//LamdaDemo.DemoC();
//LamdaDemo.DemoD();
////LamdaDemo.DemoE();
//LamdaDemo.DemoF();
//LamdaDemo.TestEcho();
//LamdaDemo.TestDotrans();
//ThreadDemo.DemoCurrentTH();
//ThreadDemo.DemoA();
//ThreadDemo.DemoB();
//ThreadDemo.DemoB1();
//ThreadDemo.DemoC();
//TestEvents.TestOne();
//StreamLesson.TestOne();
//StreamLesson.TestTwo();
//StreamReaderWriterLesson.MemStreamReader();
//StreamReaderWriterLesson.MemStreamWriter();

//StreamReaderWriterLesson.WriteBytesToMemoryStream();
//StreamReaderWriterLesson.ReadBytesFromMemoryStream();
//StreamReaderWriterLesson.ReadStringFromMemoryStream();
//StreamReaderWriterLesson.WriteStringToMemoryStream();
//StreamReaderWriterLesson.PeekAndReadCharacters();
//FileOperator.FileWriteAllLines();
//FileOperator.ListDirectoryContent();
//FileOperator.ShowCurrentDirectory();
//  FileOperator.StreamWriterDemo();
//FileOperator.StreamReaderFromFileDemo();
/////////////////////////////////////FileOperator.Logo();
//TestBinaryFormatter.SerializeCustomer();
//ClassA.TaskMethodA();
//TaskLessons.TestOne();
/////////////////ClassA.TaskMethodB();
/////////////////ClassA.TaskMethodB1();
/////////////////ClassA.TaskMethodC();
//ClassA.ParentTask();
//ClassA.ChildTask();
//TaskLessons.TestCancelToken();
TaskLessons.ContinueTask();
Console.ReadLine();
